### ISSUE TITLE
Checkout path dependency in git dependency

### ISSUE THREAD

**Issue by phsauter** [pulp-platform/bender#125]
When you have a git repo as a dependency with one Bender Manifest on its top-level (eg for the whole chip) and another one in a sub-directory, eg generated from a tool like [Padrick](https://github.com/pulp-platform/padrick), then the following happens:

- There is a note warning that this case isn't fully supported but only when doing `bender update` not `bender checkout`
- `bender update` actually seems to work fine
- Doing `bender checkout` with an already existing `Bender.lock` file (as you would do to ensure everyone is using the same dependencies), then the repo will get checked out but the path in the `Bender.lock` file is not updated.
- It does give a warning at the end: `Name issue with "sub-directory", export_include_dirs not handled. Could relate to name mismatch, see bender update`

What happens is that running `bender checkout` (can) change the dependencies hash (?) at the end of the directory name inside `.bender/git/checkouts` but it does not update the path for the path-dependency while doing so. This breaks the path dependency.

The warning is also rather confusing and might not even show up if the `export_include_dirs` feature is not used.

Ideally this would be fixed by changing the behavior of `bender checkout` so it either always used the same hashes (?) when called on the same `Bender.lock` file (which would mean the path-dependency stays valid) or it should update the path dependency in the `Bender.lock` file or resolve the invalidated path in another way (eg by using links in the internal `.bender` structure.

If this is not something you want to support, then I would at least add the `bender update` warning for this case to `bender checkout` as well.

**Comment by micprog** [comment]
For `path` dependencies in a `git` dependency, there is an issue when attempting to resolve dependencies. Namely, bender attempts to follow the path of said path dependency to find the manifest (Bender.yml file). However, if the parent dependency (git repository) is not checked out yet, it will not correctly find the file, as the path does not exist yet. This can be avoided by ensuring the dependencies are checked out (i.e., by running `bender checkout`). However, it may require `bender update` to be run more than once to ensure proper version resolution in case this path sub-dependency updates its manifest. In older versions of bender (<0.26) this did not work correctly, originally fixed in https://github.com/pulp-platform/bender/pull/98.

For further info, if the `Bender.lock` file exists and the `Bender.yml` of the top project was not updated, then the lock file will not be changed, and bender will use the dependencies linked in the .lock file. This is what it is there for. To update the .lock file, run `bender update`.

> It does give a warning at the end: `Name issue with "sub-directory", export_include_dirs not handled. Could relate to name mismatch, see bender update`

This relates to the name requesting the package being different from the name indicated within the package. `bender update` should warn about this issue. With this, there are multiple ways for dependencies to be referenced internally, causing possibly unclear references, especially for the `export_include_dirs` feature, which bender internally now has no reference to as it cannot find the corresponding package, and thus does not know if you are using it or not, so it warns nonetheless.

> What happens is that running `bender checkout` (can) change the dependencies hash (?) at the end of the directory name inside `.bender/git/checkouts` but it does not update the path for the path-dependency while doing so. This breaks the path dependency.
> 
> Ideally this would be fixed by changing the behavior of bender checkout so it either always used the same hashes (?) when called on the same Bender.lock file (which would mean the path-dependency stays valid) or it should update the path dependency in the Bender.lock file or resolve the invalidated path in another way (eg by using links in the internal .bender structure.

As far as I know, the used hashes should remain consistent (see https://github.com/pulp-platform/bender/blob/master/src/sess.rs#L662-L685). Please let me know if this is not the case. Also, the hash does not relate to the commit hash used, only the repository URL. Therefore, a dependency path should remain consistent when only running `bender checkout`, and the lock file does not need to be updated.

I hope this answers your question, let me know if not.
